# Generated by Django 2.2.6 on 2019-12-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=30)),
                ('db_ip', models.GenericIPAddressField()),
                ('db_port', models.IntegerField()),
                ('account', models.CharField(max_length=30)),
                ('env', models.IntegerField(choices=[(1, '生产'), (2, '测试')])),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
