# Generated by Django 2.2.6 on 2019-12-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='env',
            field=models.CharField(choices=[('1', '生产'), ('2', '测试')], max_length=1),
        ),
    ]
