# Generated by Django 2.2.6 on 2019-12-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191211_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='env',
            field=models.CharField(max_length=2),
        ),
    ]
